name: Commit and push
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1,3,20 * *'

jobs:
  commit-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "TORIFUKUKaiou"
          git config user.email "torifuku.kaiou@gmail.com"
          git commit --allow-empty -m "empty commit"
          git push origin main
      - name: git push gigalixir
        run: |
          git remote add gigalixir https://${{ secrets.GIGALIXIR_EMAIL }}:${{ secrets.GIGALIXIR_API_KEY }}@git.gigalixir.com/${{ secrets.GIGALIXIR_APP_NAME }}.git
          git push -f gigalixir HEAD:refs/heads/main